import { loadPrompt } from "./prompt-loader";
import { isTrivialConversationalTurn } from "./turn-triage";
import { PersistentConductor, PersistentConductorError } from "./persistent-conductor";

export type TaskType = "code_review" | "debug" | "refactor" | "general" | "plan" | "research" | "test" | "docs";
export type Complexity = "low" | "medium" | "high";
export type StageName = "planner" | "executor" | "reviewer" | "rewriter" | "synthesizer";
export type Topology = "linear" | "speculative_parallel" | "speculative_cascade" | "recursive";
export type CoordinatorStageDecision = StageName | null | `re-enter:${StageName}`;

export interface ChatMessage {
  role: string;
  content: string;
  tool_calls?: any;
  tool_call_id?: string;
  name?: string;
}

export type CallModelFn = (
  messages: Array<ChatMessage>,
  options?: {
    temperature?: number;
    max_tokens?: number;
    stream?: boolean;
    onChunk?: (chunk: string) => void;
    tools?: any[];
    stageLabel?: string;
    cascadeTier?: "cheap" | "strong";
    surfaceAsAnswer?: boolean;
    suppressActivity?: boolean;
  }
) => Promise<{ content: string; tool_calls?: any[] }>;

export interface CoordinatorContext {
  needs_workspace_inspection: boolean;
  needs_memory: boolean;
  estimated_complexity: Complexity;
}

export interface WorkerInstructions {
  planner?: string;
  executor?: string;
  reviewer?: string;
  rewriter?: string;
  synthesizer?: string;
}

export interface SharedContextHints {
  relevant_memories?: string[];
  prior_tool_results?: Record<string, string>;
  failure_patterns?: string[];
}

export interface CoordinatorResult {
  task_type: TaskType;
  pipeline: CoordinatorStageDecision[];
  topology: Topology;
  context: CoordinatorContext;
  coordinator_rationale: string;
  /** Per-stage task-specific instructions generated by the conductor. */
  worker_instructions?: WorkerInstructions;
  /** Cross-turn context the conductor wants injected into worker prompts. */
  shared_context?: SharedContextHints;
  /** Phase 4 telemetry: which routing backend produced this decision. */
  conductor_source?: "local" | "api" | "trivial";
  conductor_model?: string;
}

export interface CoordinatorRouteOptions {
  sessionId: string;
  history?: ChatMessage[];
  lastOutcome?: string;
  /** Inter-workflow shared memory injected into conductor routing turns. */
  sessionMemoryHints?: SharedContextHints;
}

interface CoordinatorState {
  sessionId: string;
  turns: number;
  lastOutcome?: string;
  lastDecision?: CoordinatorResult;
}

export class CoordinatorError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CoordinatorError";
  }
}

const VALID_TASK_TYPES = new Set<TaskType>(["code_review", "debug", "refactor", "general", "plan", "research", "test", "docs"]);
const VALID_COMPLEXITIES = new Set<Complexity>(["low", "medium", "high"]);
const VALID_STAGES = new Set<StageName>(["planner", "executor", "reviewer", "rewriter", "synthesizer"]);
const VALID_TOPOLOGIES = new Set<Topology>(["linear", "speculative_parallel", "speculative_cascade", "recursive"]);

export class Coordinator {
  private static readonly MAX_STATES = 256;
  private static readonly states = new Map<string, CoordinatorState>();

  constructor(
    private callModel: CallModelFn,
    private persistentConductor?: PersistentConductor,
  ) {}

  async route(request: string, options: CoordinatorRouteOptions): Promise<CoordinatorResult> {
    if (isTrivialConversationalTurn(request)) {
      const state = this.getState(options.sessionId);
      const decision = { ...this.conversationalRoute(), conductor_source: "trivial" as const };
      state.turns += 1;
      state.lastDecision = decision;
      return decision;
    }

    const state = this.getState(options.sessionId);
    const lastOutcome = options.lastOutcome ?? state.lastOutcome;
    const response = await this.invokeCoordinatorModel(request, {
      sessionId: options.sessionId,
      turnNumber: state.turns + 1,
      lastOutcome,
      history: options.history,
      sessionMemoryHints: options.sessionMemoryHints,
    });

    // Resilient routing: a coordinator model that returns empty/garbled output
    // (e.g. a reasoning model that spends its budget on <think> and emits no
    // JSON content) must NOT kill the turn. Fall back to a safe default route
    // so the pipeline always proceeds to a streamed answer. This is the
    // coordinator-level complement to the cross-provider model fallback.
    let decision: CoordinatorResult;
    try {
      const parsed = this.extractJson<unknown>(response.content);
      decision = this.validate(parsed);
    } catch (e) {
      console.warn(`[Coordinator] Routing parse failed, using default route: ${e instanceof Error ? e.message : String(e)}`);
      decision = this.defaultRoute();
    }
    decision.conductor_source = response.source;
    decision.conductor_model = response.model;
    state.turns += 1;
    state.lastOutcome = options.lastOutcome ?? state.lastOutcome;
    state.lastDecision = decision;
    Coordinator.states.delete(options.sessionId);
    Coordinator.states.set(options.sessionId, state);
    this.pruneStates();
    return decision;
  }

  /**
   * Safe default route when the coordinator model output can't be parsed into a
   * valid decision.
   *
   * The fallback goes straight to a single `synthesizer` stage. Rationale (from
   * the 2026-06-26 live diagnosis in `docs/NEXT_AGENT_JARVIS_LIVE_MODEL_DIAGNOSIS_2026-06-26.md`):
   *   - The coordinator's "I'm broken" signal almost always means the
   *     planner/executor models are also degrading (the same provider/model
   *     pool fails to emit usable JSON in 6+ seconds).
   *   - Routing through `planner → executor → synthesizer` on the fallback path
   *     would (a) leak internal planner task text into the user-visible
   *     stream, (b) compound the first-token timeouts we already see in those
   *     stages, and (c) produce noisier / less reliable answers than a direct
   *     synthesizer pass.
   *   - The synthesizer stage is the one guaranteed to emit a streamed answer
   *     (the user always sees a final bubble), and the routing for that stage
   *     is already model-pool aware.
   *
   * So the safe default is: skip the planning stages we know are misbehaving,
   * and let the synthesizer produce a best-effort direct answer. The session
   * history + memory context are still passed through, so a follow-up turn can
   * re-engage the planner if the user wants something more structured.
   */
  private async invokeCoordinatorModel(
    request: string,
    options: {
      sessionId: string;
      turnNumber: number;
      lastOutcome?: string;
      history?: ChatMessage[];
      sessionMemoryHints?: SharedContextHints;
    },
  ): Promise<{ content: string; source: "local" | "api"; model?: string }> {
    const conductor = this.persistentConductor;
    if (conductor) {
      try {
        if (await conductor.isAvailable()) {
          const local = await conductor.routeTurn({
            sessionId: options.sessionId,
            request,
            turnNumber: options.turnNumber,
            lastOutcome: options.lastOutcome,
            recentHistory: options.history,
            sessionMemoryHints: options.sessionMemoryHints,
          });
          console.log(
            `[Coordinator] Local conductor routed turn ${options.turnNumber} for ${options.sessionId} ` +
            `via ${local.model} in ${local.latencyMs}ms`,
          );
          return { content: local.content, source: "local", model: local.model };
        }
      } catch (e) {
        const message = e instanceof Error ? e.message : String(e);
        if (!conductor.shouldFallbackToApi()) {
          throw e instanceof PersistentConductorError ? e : new CoordinatorError(message);
        }
        console.warn(`[Coordinator] Local conductor failed, falling back to API coordinator: ${message}`);
      }
    }

    const coordinatorPrompt = loadPrompt("coordinator.md");
    const history = (options.history ?? [])
      .slice(-8)
      .map((m) => `[${m.role.toUpperCase()}]: ${m.content.slice(0, 1200)}${m.content.length > 1200 ? "..." : ""}`)
      .join("\n");

    if (conductor) {
      conductor.markApiFallback(options.sessionId);
    }

    const api = await this.callModel([
      { role: "system", content: coordinatorPrompt },
      {
        role: "user",
        content: [
          `Session ID: ${options.sessionId}`,
          `Coordinator turn: ${options.turnNumber}`,
          `Last outcome: ${options.lastOutcome ?? "none"}`,
          history ? `Recent session history:\n${history}` : "Recent session history: none",
          `Current request:\n${request}`,
        ].join("\n\n"),
      },
    ], {
      temperature: 0.1,
      max_tokens: 700,
      stageLabel: "coordinator",
      suppressActivity: true,
    });
    return { content: api.content, source: "api" };
  }

  private defaultRoute(): CoordinatorResult {
    return {
      task_type: "general",
      pipeline: ["synthesizer"],
      topology: "linear",
      context: {
        needs_workspace_inspection: false,
        needs_memory: true,
        estimated_complexity: "medium",
      },
      coordinator_rationale:
        "Default route (coordinator output was unparseable): skipping planner/executor and going straight to a streamed synthesizer answer.",
    };
  }

  private conversationalRoute(): CoordinatorResult {
    return {
      task_type: "general",
      pipeline: ["synthesizer"],
      topology: "linear",
      context: {
        needs_workspace_inspection: false,
        needs_memory: false,
        estimated_complexity: "low",
      },
      coordinator_rationale: "Trivial conversational turn — direct synthesizer reply.",
    };
  }

  executablePipeline(decision: CoordinatorResult): StageName[] {
    const stages: StageName[] = [];
    for (const step of decision.pipeline) {
      if (!step) continue;
      const stage = step as string;
      if (stage.startsWith("re-enter:")) {
        stages.push(stage.slice("re-enter:".length) as StageName);
      } else {
        stages.push(stage as StageName);
      }
    }
    return stages.length > 0 ? stages : ["synthesizer"];
  }

  private getState(sessionId: string): CoordinatorState {
    const existing = Coordinator.states.get(sessionId);
    if (existing) {
      Coordinator.states.delete(sessionId);
      Coordinator.states.set(sessionId, existing);
      return existing;
    }
    const state: CoordinatorState = { sessionId, turns: 0 };
    Coordinator.states.set(sessionId, state);
    this.pruneStates();
    return state;
  }

  private pruneStates() {
    while (Coordinator.states.size > Coordinator.MAX_STATES) {
      const oldest = Coordinator.states.keys().next().value;
      if (!oldest) break;
      Coordinator.states.delete(oldest);
    }
  }

  private validate(raw: unknown): CoordinatorResult {
    if (!raw || typeof raw !== "object") {
      throw new CoordinatorError("Coordinator returned non-object JSON");
    }
    const obj = raw as Record<string, any>;
    if (!VALID_TASK_TYPES.has(obj.task_type)) {
      throw new CoordinatorError(`Coordinator returned invalid task_type: ${String(obj.task_type)}`);
    }
    if (!Array.isArray(obj.pipeline)) {
      throw new CoordinatorError("Coordinator returned invalid pipeline");
    }
    const pipeline = obj.pipeline.map((step: unknown) => this.validateStageDecision(step));
    const topology = VALID_TOPOLOGIES.has(obj.topology) ? obj.topology as Topology : "linear";
    const context = obj.context ?? {};
    const estimated = VALID_COMPLEXITIES.has(context.estimated_complexity) ? context.estimated_complexity as Complexity : "medium";
    return {
      task_type: obj.task_type,
      pipeline,
      topology,
      context: {
        needs_workspace_inspection: context.needs_workspace_inspection ?? false,
        needs_memory: context.needs_memory ?? true,
        estimated_complexity: estimated,
      },
      coordinator_rationale: typeof obj.coordinator_rationale === "string"
        ? obj.coordinator_rationale
        : typeof obj.routing_rationale === "string"
          ? obj.routing_rationale
          : "Coordinator selected a route.",
      worker_instructions: this.validateWorkerInstructions(obj.worker_instructions),
      shared_context: this.validateSharedContext(obj.shared_context),
    };
  }

  private validateWorkerInstructions(raw: unknown): WorkerInstructions | undefined {
    if (!raw || typeof raw !== "object") return undefined;
    const obj = raw as Record<string, unknown>;
    const out: WorkerInstructions = {};
    for (const stage of VALID_STAGES) {
      const value = obj[stage];
      if (typeof value === "string" && value.trim()) {
        out[stage] = value.trim();
      }
    }
    return Object.keys(out).length > 0 ? out : undefined;
  }

  private validateSharedContext(raw: unknown): SharedContextHints | undefined {
    if (!raw || typeof raw !== "object") return undefined;
    const obj = raw as Record<string, unknown>;
    const out: SharedContextHints = {};

    if (Array.isArray(obj.relevant_memories)) {
      const memories = obj.relevant_memories
        .filter((m): m is string => typeof m === "string" && m.trim().length > 0)
        .map((m) => m.trim());
      if (memories.length > 0) out.relevant_memories = memories;
    }

    if (Array.isArray(obj.failure_patterns)) {
      const patterns = obj.failure_patterns
        .filter((p): p is string => typeof p === "string" && p.trim().length > 0)
        .map((p) => p.trim());
      if (patterns.length > 0) out.failure_patterns = patterns;
    }

    if (obj.prior_tool_results && typeof obj.prior_tool_results === "object") {
      const cached: Record<string, string> = {};
      for (const [key, value] of Object.entries(obj.prior_tool_results as Record<string, unknown>)) {
        if (typeof value === "string" && value.trim()) {
          cached[key] = value.trim();
        }
      }
      if (Object.keys(cached).length > 0) out.prior_tool_results = cached;
    }

    return Object.keys(out).length > 0 ? out : undefined;
  }

  private validateStageDecision(step: unknown): CoordinatorStageDecision {
    if (step === null) return null;
    if (typeof step !== "string") {
      throw new CoordinatorError(`Coordinator returned non-string stage decision: ${String(step)}`);
    }
    if (VALID_STAGES.has(step as StageName)) return step as StageName;
    if (step.startsWith("re-enter:")) {
      const stage = step.slice("re-enter:".length);
      if (VALID_STAGES.has(stage as StageName)) return step as `re-enter:${StageName}`;
    }
    throw new CoordinatorError(`Coordinator returned invalid stage decision: ${step}`);
  }

  private extractJson<T>(text: string): T {
    try {
      return JSON.parse(text.trim()) as T;
    } catch {}

    const start = text.indexOf("{");
    const end = text.lastIndexOf("}");
    if (start !== -1 && end !== -1 && end > start) {
      const jsonStr = text.substring(start, end + 1);
      try {
        return JSON.parse(jsonStr) as T;
      } catch {}
    }
    throw new CoordinatorError(`Failed to parse JSON from coordinator output: ${text}`);
  }
}
