import type { OrchestrationTheta } from "./orchestration-policy";

/** Direct decision owners for each inventory-approved runtime policy dimension. */
export const THETA_DECISION_OWNERS: Record<keyof OrchestrationTheta, readonly string[]> = {
  force_write_nudge_cap: ["orchestration/mid-loop-intervention.ts"],
  max_quality_pushes: ["orchestration/pipeline.ts", "orchestration/mid-loop-intervention.ts"],
  max_mid_loop_checks: ["orchestration/mid-loop-intervention.ts"],
  max_mid_loop_escalations: ["orchestration/conductor.ts", "orchestration/mid-loop-intervention.ts"],
  reserved_mid_loop_escalations: ["orchestration/mid-loop-intervention.ts"],
  mid_loop_endgame_budget_ms: ["orchestration/mid-loop-intervention.ts"],
  mid_loop_endgame_turn_ratio: ["orchestration/mid-loop-intervention.ts"],
  max_failed_write_attempts_without_effect: ["orchestration/effect-gate.ts"],
  identical_write_pressure_note_cap: ["orchestration/effect-gate.ts"],
  repeated_failed_writes_threshold: ["orchestration/delegate-intervention-policy.ts"],
  max_directives_per_turn: ["orchestration/directive-budget.ts"],
  default_max_reroutes_per_segment: ["orchestration/reroute-policy.ts"],
  local_stage_min_window_ms: ["orchestration/agent-pool.ts"],
  synthesis_runway_ms: ["orchestration/pipeline.ts"],
  routing_timeout_ms: ["orchestration/persistent-conductor.ts"],
  no_tool_retry_budget_floor_ms: ["orchestration/executor-progress-policy.ts"],
  no_tool_ratio_ceiling: ["orchestration/executor-progress-policy.ts"],
  no_tool_ratio_min_turns: ["orchestration/executor-progress-policy.ts"],
  min_no_tool_sample: ["orchestration/model-health.ts"],
  no_tool_demotion_threshold: ["orchestration/model-health.ts"],
  min_error_rate_sample: ["orchestration/model-health.ts"],
  error_rate_bench_threshold: ["orchestration/model-health.ts"],
  trial_sample_target: ["orchestration/model-trial-policy.ts"],
  reliability_latency_min_samples: ["orchestration/reliability-latency-rank.ts"],
  max_delegate_launches_per_run: ["orchestration/pipeline.ts"],
  default_free_thrash_threshold: ["orchestration/delegate-model-select.ts"],
  delegate_write_scoreboard_bench_attempts: ["orchestration/delegate-model-select.ts"],
  thrash_ttl_ms: ["orchestration/delegate-model-select.ts", "orchestration/pipeline.ts"],
  delegate_health_cooldown_ms: ["orchestration/claude-delegate.ts"],
  delegate_availability_cache_ms: ["orchestration/claude-delegate.ts"],
  delegate_api_retry_abort_threshold: ["orchestration/claude-delegate.ts"],
  max_handoff_seed_paths: ["orchestration/delegate-handoff-seed.ts"],
  deep_read_min_content_reads: ["orchestration/evidence-sufficiency.ts"],
  max_grounding_symbols: ["orchestration/symbol-grounding.ts"],
  max_grounding_greps: ["orchestration/symbol-grounding.ts"],
  grounding_grep_head_limit: ["orchestration/symbol-grounding.ts"],
  grounding_block_context_chars: ["orchestration/symbol-grounding.ts"],
  executor_tool_result_context_chars: ["orchestration/context-budget.ts", "orchestration/pipeline.ts"],
  executor_preflight_result_context_chars: ["orchestration/context-budget.ts", "orchestration/pipeline.ts"],
  write_turn_tool_result_context_chars: ["orchestration/context-budget.ts", "orchestration/pipeline.ts"],
  executor_transcript_budget_tokens: ["orchestration/context-budget.ts", "orchestration/pipeline.ts"],
  write_turn_transcript_budget_tokens: ["orchestration/context-budget.ts", "orchestration/pipeline.ts"],
  repetition_similarity_threshold: ["orchestration/repetition-guard.ts"],
  default_min_viable_stage_ms: ["orchestration/turn-budget.ts"],
  progress_extension_ms: ["orchestration/turn-budget.ts"],
  stage_extension_ceiling_ms: ["orchestration/turn-budget.ts"],
  absolute_turn_cap_ms: ["orchestration/turn-budget.ts"],
  model_scorecard_window_size: ["orchestration/model-scorecard.ts"],
  model_scorecard_unfit_error_rate: ["orchestration/model-scorecard.ts"],
  default_max_repair_cycles: ["orchestration/runtime-loop.ts"],
  max_review_repair_rounds_cap: ["orchestration/pipeline.ts"],
  dead_tool_suppress_threshold: ["orchestration/dead-tool-suppression.ts"],
};
